services:
  phpdish.admin.user:
        class: PHPDish\Bundle\AdminBundle\Admin\UserAdmin
        arguments: [~, PHPDish\Bundle\UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 用户 }
        public: true

  phpdish.admin.wallet:
        class: PHPDish\Bundle\AdminBundle\Admin\WalletAdmin
        arguments: [~, PHPDish\Bundle\PaymentBundle\Entity\Wallet, ~]
        calls:
            - {method: addChild, arguments: ['@phpdish.admin.payment']}
        tags:
            - { name: sonata.admin, manager_type: orm, label: 钱包 }
        public: true

  phpdish.admin.payment:
        class: PHPDish\Bundle\AdminBundle\Admin\PaymentAdmin
        arguments: [~, PHPDish\Bundle\PaymentBundle\Entity\Payment, PHPDishAdminBundle:Payment]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 流水 }
        public: true
        calls:
            - {method: 'setTemplates', arguments: [{inner_list_row2: 'PHPDishAdminBundle:Admin:inner_row_comment.html.twig',base_list_field: 'SonataAdminBundle:CRUD:base_list_field.html.twig'}]}


  phpdish.admin.category:
        class: PHPDish\Bundle\AdminBundle\Admin\CategoryAdmin
        arguments: [~, PHPDish\Bundle\PostBundle\Entity\Category, ~]
        calls:
            - {method: addChild, arguments: ['@phpdish.admin.post']}
        tags:
            - { name: sonata.admin, manager_type: orm, label: 专栏 }
        public: true

  phpdish.admin.post:
        class: PHPDish\Bundle\AdminBundle\Admin\PostAdmin
        arguments: [~, PHPDish\Bundle\PostBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 文章 }
        public: true

  phpdish.admin.thread:
        class: PHPDish\Bundle\AdminBundle\Admin\ThreadAdmin
        arguments: [~, PHPDish\Bundle\ForumBundle\Entity\Thread, ~]
        calls:
            - {method: addChild, arguments: ['@phpdish.admin.topic']}
        tags:
            - { name: sonata.admin, manager_type: orm, label: 节点 }
        public: true

  phpdish.admin.topic:
        class: PHPDish\Bundle\AdminBundle\Admin\TopicAdmin
        arguments: [~, PHPDish\Bundle\ForumBundle\Entity\Topic, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 话题 }
        public: true

  phpdish.admin.friend_link:
        class: PHPDish\Bundle\AdminBundle\Admin\FriendLinkAdmin
        arguments: [~, PHPDish\Bundle\CoreBundle\Entity\FriendLink, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 友情链接 }
        public: true

  phpdish.admin.song:
        class: PHPDish\Bundle\AdminBundle\Admin\SongAdmin
        arguments: [~, PHPDish\Bundle\WebBundle\Entity\Song, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 每天一首歌 }
        public: true
