services:
#    php_dish_post.example:
#        class: PHPDish\Bundle\PostBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    phpdish.manager.post:
        class: PHPDish\Bundle\PostBundle\Service\PostManager
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'
            - '@markdown.parser'

    phpdish.manager.category:
        class: PHPDish\Bundle\PostBundle\Service\CategoryManager
        arguments:
            - '@doctrine.orm.entity_manager'

    phpdish.manager.post.comment:
        class: PHPDish\Bundle\PostBundle\Service\CommentManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@markdown.parser"
            - "@phpdish.mention.parser"

    phpdish.form.type.post:
         class: PHPDish\Bundle\PostBundle\Form\Type\PostType
         arguments: ['@phpdish.manager.category']
         tags:
             - { name: form.type }

    phpdish.security.post_voter:
        class: PHPDish\Bundle\PostBundle\Security\PostVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false