services:
#    php_dish_post.example:
#        class: PHPDish\Bundle\PostBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    post.post_manager:
        class: PHPDish\Bundle\PostBundle\Service\PostManager
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'

    post.comment_manager:
        class: PHPDish\Bundle\PostBundle\Service\PostCommentManager
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'