# PHPDish Mention Adapter
services:
    phpdish.security.password_encoder.generic:
        class: PHPDish\Bundle\CoreBundle\Security\Core\Encoder\GenericPasswordEncoder
        arguments: ['%security.password_encoder_strength%']

    phpdish.mention.adapter:
        class: PHPDish\Bundle\UserBundle\Mention\Adapter
        arguments: ['@phpdish.manager.user', '@router']

    phpdish.mention.parser:
        class: PHPDish\Component\Mention\MentionParser
        arguments: ['@phpdish.mention.adapter']

    phpdish.body_processor:
        class: PHPDish\Component\Core\BodyProcessor\BodyProcessor
        arguments:
            - "@markdown.parser"
            - "@phpdish.mention.parser"
            - "@exercise_html_purifier.default"

    phpdish.http_client:
        class: GuzzleHttp\Client
        arguments:
            - {verify: false}

    phpdish.qcloud_factory:
        class: PHPDish\Component\QCloud\QCloudFactory
        arguments: ['%qcloud.secret_id%', '%qcloud.secret_key%']

    phpdish.pinyin_translator:
        class: Overtrue\Pinyin\Pinyin

    phpdish.html_chunker:
        class: PHPDish\Component\Util\HtmlChunker
        arguments: ['@exercise_html_purifier.default']