# PHPDish Mention Adapter
services:
    phpdish.mention.adapter:
        class: PHPDish\Bundle\UserBundle\Mention\Adapter
        arguments: ['@phpdish.manager.user', '@router']

    phpdish.mention.parser:
        class: PHPDish\Component\Mention\MentionParser
        arguments: ['@phpdish.mention.adapter']

    phpdish.body_processor:
        class: PHPDish\Component\Core\BodyProcessor\BodyProcessor
        arguments:
            - "@markdown.parser"
            - "@phpdish.mention.parser"