services:
  phpdish.installer.directory_checker:
      class: PHPDish\Bundle\CoreBundle\Installer\Checker\DirectoryChecker
      arguments:
          - '@filesystem'

  phpdish.installer.requirements:
        class: PHPDish\Bundle\CoreBundle\Installer\Requirement\PHPDishRequirements

  phpdish.installer.requirements_checker:
      class: PHPDish\Bundle\CoreBundle\Installer\Checker\RequirementsChecker
      arguments:
          - '@phpdish.installer.requirements'