PHPDish\Bundle\PostBundle\Entity\Comment:
    exclusion_policy: ALL
    xml_root_name: comment
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        voteCount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        post:
            expose: true
            type: PHPDish\Bundle\PostBundle\Entity\Post
            groups: [Detailed]
