PHPDish\Bundle\PostBundle\Entity\Comment:
    exclusion_policy: ALL
    xml_root_name: comment
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        body:
            expose: true
            type: string
            groups: [Default, Detailed]
        originalBody:
            expose: true
            type: string
            groups: [Default, Detailed]
        voteCount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        enabled:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        createdAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        user:
            expose: true
            type: PHPDish\Bundle\UserBundle\Entity\User
            groups: [Detailed]
        post:
            expose: true
            type: PHPDish\Bundle\PostBundle\Entity\Post
            groups: [Detailed]
