phpdish_main:
    resource: '@PHPDishCoreBundle/Resources/config/routing.yml'

easy_admin:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /manager

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin