_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

php_dish_media:
    resource: "@PHPDishMediaBundle/Controller"
    prefix:   /
    type: annotation

php_dish_web:
    resource: "@PHPDishWebBundle/Controller/"
    prefix: /
    type: annotation

php_dish_post:
    resource: "@PHPDishPostBundle/Controller/"
    prefix: /
    type: annotation

php_dish_user:
    resource: "@PHPDishUserBundle/Controller/"
    prefix: /
    type: annotation

php_dish_user_ex:
    resource: "@PHPDishUserBundle/Resources/config/routing.yml"

php_dish_forum:
    resource: "@PHPDishForumBundle/Controller/"
    prefix: /
    type: annotation

php_dish_notification:
    resource: "@PHPDishNotificationBundle/Controller/"
    prefix: /
    type: annotation

php_dish_chat:
    resource: "@PHPDishChatBundle/Controller"
    prefix:   /
    type: annotation

php_dish_resume:
    resource: "@PHPDishResumeBundle/Controller"
    prefix:   /
    type: annotation

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /chats

#php_dish_admin:
#    resource: "@PHPDishAdminBundle/Controller/"
#    prefix: /admin
#    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

weibo_login:
    path: "/login/check-weibo"

github_login:
    path: "/login/check-github"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /admin
