_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

php_dish_media:
    resource: "@PHPDishMediaBundle/Controller"
    prefix:   /
    type: annotation

php_dish_comment:
    resource: "@PHPDishCommentBundle/Controller/"
    prefix:   /
    type: annotation

php_dish_web:
    resource: "@PHPDishWebBundle/Controller/"
    prefix: /
    type: annotation

php_dish_post:
    resource: "@PHPDishPostBundle/Controller/"
    prefix: /
    type: annotation

php_dish_user:
    resource: "@PHPDishUserBundle/Controller/"
    type: annotation

php_dish_forum:
    resource: "@PHPDishForumBundle/Controller/"
    prefix: /
    type: annotation

php_dish_admin:
    resource: "@PHPDishAdminBundle/Controller/"
    prefix: /admin
    type: annotation

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }