# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        PHPDish\Bundle\UserBundle\Model\UserInterface:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        phpdish:
            entity:
                class: PHPDishUserBundle:User
                property: username
                manager_name: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                provider: phpdish
            logout:
                path: logout
                target: homepage
            anonymous:  ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/write, role: ROLE_USER }
        - { path: ^/settings, role: ROLE_USER }