services:
#    php_dish_forum.example:
#        class: PHPDish\Bundle\ForumBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    phpdish.manager.thread:
       class: PHPDish\Bundle\ForumBundle\Service\ThreadManager
       arguments: ["@doctrine.orm.entity_manager"]

    phpdish.manager.topic:
        class: PHPDish\Bundle\ForumBundle\Service\TopicManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@markdown.parser"
            - "@phpdish.mention.parser"

    phpdish.manager.reply:
        class: PHPDish\Bundle\ForumBundle\Service\ReplyManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@event_dispatcher'
            - "@markdown.parser"
            - "@phpdish.mention.parser"

    phpdish.form.topic_type:
        class: PHPDish\Bundle\ForumBundle\Form\Type\TopicType
        arguments: ["@phpdish.manager.thread"]
        tags:
           - {name: "form.type"}

    phpdish.security.topic_voter:
        class: PHPDish\Bundle\ForumBundle\Security\TopicVoter
        arguments:
            - "@security.access.decision_manager"
        tags:
            - {name: "security.voter"}
        public: false

    phpdish.security.topic_reply_voter:
        class: PHPDish\Bundle\ForumBundle\Security\TopicReplyVoter
        arguments:
            - "@security.access.decision_manager"
        tags:
            - {name: "security.voter"}
        public: false
