PHPDish\Bundle\ForumBundle\Entity\Thread:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: [slug]
             message: '该slug已经被占用'

    properties:
       name:
           - NotBlank:
               message: 名称不得为空
           - Length:
               min: 2
               max: 50
               minMessage: '名称至少{{ limit }}字符长度'
               maxMessage: '名称最多{{ limit }}字符长度'

       slug:
           - NotBlank:
               message: Slug不得为空

       description:
           - Length:
                 max: 500
                 maxMessage: '描述最多{{ limit }}字符长度'


PHPDish\Bundle\ForumBundle\Entity\Topic:
    properties:
        title:
            - NotBlank:
                message: '标题不得为空'
            - Length:
                 min: 10
                 max: 150
                 minMessage: '标题至少{{ limit }}字符长度'
                 maxMessage: '标题最多{{ limit }}字符长度'

        originalBody:
            - NotBlank:
                 message: '内容不得为空'
            - Length:
                 min: 10
                 minMessage: '内容至少{{ limit }}字符长度'

        threads:
            - NotBlank:
                message: '节点不得为空'