services:
#    php_dish_notification.example:
#        class: PHPDish\Bundle\NotificationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    phpdish.manager.notification:
        class: PHPDish\Bundle\NotificationBundle\Service\NotificationManager
        arguments:
            - "@doctrine.orm.entity_manager"

    phpdish.manager.timeline:
        class: PHPDish\Bundle\NotificationBundle\Service\TimelineManager
        arguments:
            - "@doctrine.orm.entity_manager"
# Listeners

    phpdish.event_listener.notification.follow_user:
        class:  PHPDish\Bundle\NotificationBundle\EventListener\FollowUserListener
        arguments: ['@phpdish.manager.notification']
        tags:
            - {name: kernel.event_listener, event: user.followed, method: onUserFollowed}
        public: false


    phpdish.event_listener.notification.reply_topic:
        class:  PHPDish\Bundle\NotificationBundle\EventListener\ReplyTopicListener
        arguments: ['@phpdish.manager.notification']
        tags:
            - {name: kernel.event_listener, event: topic.replied, method: onTopicReplied}
        public: false


    phpdish.event_listener.notification.follow_category:
        class:  PHPDish\Bundle\NotificationBundle\EventListener\FollowCategoryListener
        arguments: ['@phpdish.manager.notification']
        tags:
            - {name: kernel.event_listener, event: category.followed, method: onCategoryFollowed}
        public: false

    phpdish.event_listener.notification.comment_post:
        class:  PHPDish\Bundle\NotificationBundle\EventListener\CommentPostListener
        arguments: ['@phpdish.manager.notification']
        tags:
            - {name: kernel.event_listener, event: post.commented, method: onPostCommented}
        public: false

    phpdish.event_listener.notification.mention_user:
        class:  PHPDish\Bundle\NotificationBundle\EventListener\MentionUserListener
        arguments: ['@phpdish.manager.notification']
        tags:
            - {name: kernel.event_listener, event: user.mentioned.comment, method: onUserMentionedInComment}
            - {name: kernel.event_listener, event: user.mentioned.reply, method: onUserMentionedInReply}
        public: false

# Twig Extension
    phpdish.twig_extension.notification:
       class: PHPDish\Bundle\NotificationBundle\Twig\NotificationExtension
       arguments: ['@phpdish.manager.notification', '@security.token_storage']
       tags:
           - {name: twig.extension}
       public: false