imports:
    - {resource: 'services/installer.yml'}

services:
    twig_extension.date:
         class: Twig\Extensions\DateExtension
         public: false
         tags:
            - { name: twig.extension}

    phpdish.twig_extension.url_pattern:
         class: PHPDish\Bundle\CoreBundle\Twig\UrlPatternExtension
         arguments: ['@request_stack']
         public: false
         tags:
            - { name: twig.extension}

    # Pjax
    phpdish.pjax.helper:
         class: PHPDish\Component\Pjax\Helper\PjaxHelper

    phpdish.twig_extension.pjax:
         class: PHPDish\Component\Pjax\Twig\PjaxExtension
         arguments: ['@phpdish.pjax.helper']
         public: false
         tags:
            - { name: twig.extension}

    # 核心响应事件
    phpdish.event_listener.core.kernel:
         class: PHPDish\Bundle\CoreBundle\EventListener\KernelExceptionListener
         arguments: ['@security.token_storage', '@security.authorization_checker', '@router']
         public: false
         tags:
            - { name: kernel.event_listener, event: 'kernel.exception', method: 'onKernelException', priority: 1}


   # Main Menu
    phpdish.menu_builder.main_menu:
        class: PHPDish\Bundle\CoreBundle\Menu\MainMenuBuilder
        arguments: ['@knp_menu.factory']
        tags:
           - { name: knp_menu.menu_builder, method: createMenu, alias: main_menu}