services:
    twig_extension.date:
         class: Twig\Extensions\DateExtension
         public: false
         tags:
            - { name: twig.extension}

    phpdish.twig_extension.url_pattern:
         class: PHPDish\Bundle\CoreBundle\Twig\UrlPatternExtension
         arguments: ['@request_stack']
         public: false
         tags:
            - { name: twig.extension}


   # Main Menu
    phpdish.menu_builder.main_menu:
        class: PHPDish\Bundle\CoreBundle\Menu\MainMenuBuilder
        arguments: ['@knp_menu.factory']
        tags:
           - { name: knp_menu.menu_builder, method: createMenu, alias: main_menu}