services:
    twig_extension.date:
         class: Twig\Extensions\DateExtension
         public: false
         tags:
            - { name: twig.extension}

    phpdish.twig_extension.url_pattern:
         class: PHPDish\Bundle\CoreBundle\Twig\UrlPatternExtension
         arguments: ['@request_stack']
         public: false
         tags:
            - { name: twig.extension}