services:
#    php_dish_user.example:
#        class: PHPDish\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    phpdish.manager.user:
        class: PHPDish\Bundle\UserBundle\Service\UserManager
        argguments: ["@doctrine.orm.entity_manager"]