services:
#    php_dish_user.example:
#        class: PHPDish\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    phpdish.manager.user:
        class: PHPDish\Bundle\UserBundle\Service\UserManager
        arguments:
             - '@doctrine.orm.entity_manager'
             - '@event_dispatcher'

    # PHPDish Mention Adapter
    phpdish.mention.adapter:
        class: PHPDish\Bundle\UserBundle\Mention\Adapter
        arguments: ['@phpdish.manager.user', '@router']

    phpdish.mention.parser:
        class: PHPDish\Component\Mention\MentionParser
        arguments: ['@phpdish.mention.adapter']

    phpdish.event_lsitener.user_register:
        class: PHPDish\Bundle\UserBundle\EventListener\UserRegisterListener
        arguments: ['@router']
        tags:
            - {name: kernel.event_listener, event:  fos_user.registration.success,  method: onRegisterSuccess}

    phpdish.oauth_aware.user_provider:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        class: PHPDish\Bundle\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments:
          - '@fos_user.user_manager'
          - '@phpdish.media.avatar_file_downloader'
          - {weibo: weiboId}


   # Setting Menu
    phpdish.menu_builder.setting_menu:
        class: PHPDish\Bundle\UserBundle\Menu\SettingMenuBuilder
        arguments: ['@knp_menu.factory']
        tags:
           - { name: knp_menu.menu_builder, method: createMenu, alias: setting_menu}